"""
Here we will define the schemas of the Nodes
"""

from pydantic import BaseModel, Field, AnyUrl
from typing import Optional, Union, Annotated

class BaseStructuredModel(BaseModel):
    class Config:        
        
        extra = "forbid"


class EXTRACT_USER_ARTICLE_SCHEMA(BaseStructuredModel):
    """
    It represents output of the DIFFBOT tool scrapping 
    """

    scrapped_article: Optional[Union[dict[str,str],str]] = Field(
        ...,
        description= "It is output of the DIFFBOT tool that provides us scrapped information related to article.",
    )

class ENTITIES_EXTRACTOR_SCHEMA(BaseStructuredModel):
    """
    It represents the output of the entities extracted from the article
    """

    entities: list[str] = Field(
        ...,
        description= "These are the most important entities discussed in the article"
    )

class GKP_CALLER1(BaseStructuredModel):
    """
    It represents the output of the google keyword planner - 1st call which is a list of keywords.
    """

    gkp_planner_list1:  list[dict[str, str | int | dict[str,int]]] = Field(
        ..., 
        description= "It is the list of keywords that gkp fetches "
    )

class KEYWORD_SHORTLISTER_SCHEMA(BaseStructuredModel):
    """
    It represents the output of Elbow-index dynamic threshold method to shortlist only most relevant keywords
    """
    shortlisted_keywords: list[str] = Field(
        ...,
        description= "It is the list of the keywords with highest contribution to total search volume of all keywords"
    )

class PROMPT_GENERATOR_SCHEMA(BaseStructuredModel):
    """
    It represents the list of the contextual prompts that are generated by LLMs based on the provided datapoints, It should not give more than 2 prompts.
    """
    contextual_prompts: list[str] = Field(
        ...,
        description= "It is the list of the contextual prompts"
    )

class CITED_ARTICLES_INFO(BaseStructuredModel):
    """
    It contains the field that includes the information about the cited articles, like 
    title of the articles, date, last date updated, & urls.
    """
    article_title: str = Field(
        ..., description= "It is the list of the titles of the cited articles"
    )
    article_date: str = Field(
        ..., description= "It contains the list of date of the cited article"
    )
    article_last_update: str = Field(
        ..., description= "It is the list of the date on which article was updated last time"
    )
    article_urls: str = Field(
        ..., description= "It is the list of the urls of cited articles"
    )



class CITATION_FORMAT_SCHEMA(BaseStructuredModel):
    """
    It contains the fields which are going to be the part of the information that llm will be generating in the 
    structured output
    """
    context_prompt: str = Field(
        ..., description= "It is the contextual prompt that is the part of the perplexity output"
    )
    cited_articles: list[CITED_ARTICLES_INFO] = Field(
        ..., 
        description= "It contains the list of datapoints related to the cited articles"
    )
    response_for_prompt: str = Field(
        ...,
        description= "It is the answer of perplexity for the contexual prompt - it does not include articles"
    )

class PROMPT_CITATION_FORMATTER_SCHEMA(BaseStructuredModel):
    """
    It represents the output that contains the information about contextual prompt, cited articles, and peprlexity answer
    in a cleaner format
    """
    prompts_with_citations: list[CITATION_FORMAT_SCHEMA] = Field(
        ...,
        description= "It contains the list of data points for multiple contextual prompts according to the defined format of PROMPT_CITATION_FORMAT_SCHEMA "
    )

class Prompts_cited_score_Schema(BaseStructuredModel):
    """
    It represents the fields like No. of contextual prompts for which user article was cited & list of those contextual prompts
    """
    No_of_prompts: int = Field(
        ..., description= "It is the exact number that shows how many contextual prompts are there that have cited domain or URL of user article"
    )
    list_of_prompts_cited_article: list[str] = Field(
        ..., description= "It is the list of the contextual prompts that have cited the domain or URL of user article"
    )

class citation_ranking_schema(BaseStructuredModel):
    """
    It contains the datapoints that are related to the ranking of the user article cited for prompts, ranking is relative to other cited articles.
    """    
    highest_prompt: str = Field(
        ..., description= "It contains the contextual prompt that have ranked the user article in highest rank relative to other cited article"
    )
    highest_rank: int = Field(
        ..., description="It contains the highest ranking of the citation of user article relative to other articles for contextual prompts, it takes the ranking of the prompt that have cited user article in highest rank"
    )
    lowest_prompt: str = Field(
        ..., description= "It contains the contextual prompt that have ranked the user article in lowest rank relative to other cited article"
    )
    lowest_rank: int = Field(
        ..., description= "It contains the lowest ranking of the citation of user article relative to other articles for contextual prompts, it takes the ranking of the prompt that have cited user article in lowest rank"
    )

class missed_content_details(BaseStructuredModel):
    """
    It represent the datapoints related to the missed content in the user article
    """

    missed_content: list[str] = Field(
        ..., description= "It contains the list of the core topics, ideas, key concepts, or area of focus that are present in the llm response but absent in the user article so, labelled as missed content, It should not be more than 3"
    )

    missed_content_prompt: str = Field(
        ...,
        description="Prompt that is used to get LLM response for identifying content and evidence"
    )

class GEO_METRICS_CALULATIONS(BaseStructuredModel):
    """
    It represents the output that contains different geo metrics like Prompt_cited_score, Prompts_categories
    """

    Prompt_cited_score: list[Prompts_cited_score_Schema] = Field(
        ..., description="It contains the datapoints related to the prompts_cited_score metric"
    )
    Prompts_categories: list[str] = Field(
        ..., description= "It is the list of the category assigned to contextual prompts that have cited the user article"
    )
    Citation_rank: list[citation_ranking_schema] = Field(
        ..., description= """
                            It checks the ranking of user article for all prompts that have cited it, and then check which of them prompts have cited user article in highest rank
                            and which of the prompt cited the user article as lowest rank - and gives both rank and their prompts.
                            """
    )
    Missed_content_overview: list[missed_content_details] = Field(
        ..., description= "It represent the data points related to the missed content details"
    )

class GEO_METRICS_SCHEMA(BaseStructuredModel):
    """
    It contains the output datapoints related to the geo metrics
    """
    geo_final_metrics: list[GEO_METRICS_CALULATIONS] = Field(
        ..., description= "It contains the output datapoints related to the geo metrics"
    )