"""
Here we will define the schemas of the Nodes
"""

from pydantic import BaseModel, Field, AnyUrl
from typing import Optional, Union

class BaseStructuredModel(BaseModel):
    class Config:        
        
        extra = "forbid"


class EXTRACT_USER_ARTICLE_SCHEMA(BaseStructuredModel):
    """
    It represents output of the DIFFBOT tool scrapping 
    """

    scrapped_article: Optional[Union[dict[str,str],str]] = Field(
        ...,
        description= "It is output of the DIFFBOT tool that provides us scrapped information related to article.",
    )

class ENTITIES_EXTRACTOR_SCHEMA(BaseStructuredModel):
    """
    It represents the output of the entities extracted from the article
    """

    entities: list[str] = Field(
        ...,
        description= "These are the most important entities discussed in the article"
    )

class GKP_CALLER1(BaseStructuredModel):
    """
    It represents the output of the google keyword planner - 1st call which is a list of keywords.
    """

    gkp_planner_list1:  list[dict[str, str | int | dict[str,int]]] = Field(
        ..., 
        description= "It is the list of keywords that gkp fetches "
    )

class KEYWORD_SHORTLISTER_SCHEMA(BaseStructuredModel):
    """
    It represents the output of Elbow-index dynamic threshold method to shortlist only most relevant keywords
    """
    shortlisted_keywords: list[str] = Field(
        ...,
        description= "It is the list of the keywords with highest contribution to total search volume of all keywords"
    )

class PROMPT_GENERATOR_SCHEMA(BaseStructuredModel):
    """
    It represents the list of the contextual prompts that are generated by LLMs based on the provided datapoints.
    """
    contextual_prompts: list[str] = Field(
        ...,
        description= "It is the list of the contextual prompts"
    )

class PROMPT_SEARCHER_SCHEMA(BaseStructuredModel):
    """
    It represents the output that contains the articles which LLM read to generate response and articles which are quoted in the LLM response
    """
    read_articles: list[str] = Field(
        ...,
        description= "it contains the list of the articles which LLM read to generate the response"
    )
    cited_articles: list[str] = Field(
        ...,
        description= "It contains the list of the articles which are cited by the LLM in its response"
    )